---
- name: Deploy Docker container on Ubuntu VM
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3 
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
      tags: 
        - docker

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "rishavchandel/calculator-frontend"
        tag: latest
        source: pull
        force_source: yes
      become: yes

    - name: Run Docker container
      docker_container:
        name: calculator_container
        image: "rishavchandel/calculator-frontend"
        state: started
        restart_policy: always
        published_ports:
          - "8086:80"
        container_default_behavior: "compatibility"
      ignore_errors: true
      register: docker_result
